site_name: Noah Portman
site_description: A python portfolio
site_author: noportman
site_url: https://www.noahportman.com
# repo_url: https://github.com/noportman/noportman.github.io
theme:
  name: material
  font:
    text: Roboto
    # code: Regular
  favicon: assets/images/favicon.png
  logo: assets/images/logo.png
  # icon:
  #   logo: 
  features:
    - navigation.footer
    - navigation.top
    - navigation.tabs
  custom_dir: "docs/overrides"
  language: en
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Dark mode
      primary: indigo
      accent: indigo

    # Light Mode
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Light mode
      primary: indigo
      accent: indigo

markdown_extensions:
  - admonition
  - markdown_include.include:
      base_path: docs/
  - pymdownx.details
  - attr_list
  - abbr
  - def_list
  - footnotes
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite:
  - pymdownx.snippets:
      base_path: docs/
  - pymdownx.superfences:
  - pymdownx.tabbed:
      alternate_style: true

plugins:
    - search
    - mkdocstrings
    - git-revision-date-localized:
          enable_creation_date: true
          type: timeago
    # - pdf-export
    - mkdocs-jupyter:
          include_source: True
          ignore_h1_titles: True
          execute: false
          allow_errors: false
          ignore: ["conf.py"]
          execute_ignore: ["*ignore.ipynb"]


extra:
  generator: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/noportman
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/noah-portman/

copyright: Copyright &copy; 2025 Noah Portman

nav:
  - 👋 Welcome: index.md
  - 📎 CV: cv.md
  - 📂 Samples: 
    - Samples Overview: samples/overview.md
    - WCI: samples/wci.md
    - Capstone: samples/capstone.md
    - Wetland: samples/wetland.md
    - Natural Capital: samples/natural_capital.md
  - 📓 Notebooks:
      - MIT xPRO: notebooks/mitxpro/overview.md
      - 01. Patient Scheduling: notebooks/mitxpro/01_prescriptive_data.ipynb
      - 02. Predicting Abnormal Scans: notebooks/mitxpro/02_binary_classification.ipynb
      - 03. Statistical Modeling: notebooks/mitxpro/03_prescriptive_model.ipynb
      - 04. Image Classification: notebooks/mitxpro/04_image_classification.ipynb
      - 05. Predictive Modeling: notebooks/mitxpro/05_XGBoost.ipynb
      # - Other Notebooks: notebooks/misc/overview.md
      # - 01. Folium: notebooks/misc/folium.ipynb
