site_name: Noah Portman
site_description: A python portfolio
site_author: noportman
site_url: https://www.noahportman.com
# repo_url: https://github.com/snowport/snowport.github.io
theme:
  name: material
  font:
    text: Roboto
    # code: Regular
  # favicon: assets/images/favicon.ico
  favicon: https://onnx.ai/images/icon/icon-ONNX-logo.svg
  # logo: assets/images/logo.png
  icon:
    # logo: simple/Novu
    logo: simple/onnx
    admonition:
      abstract: fontawesome/solid/book
      bug: fontawesome/solid/star
      tip: octicons/bookmark-filled-16
      warning: fontawesome/solid/certificate
  features:
    - navigation.footer
    - navigation.top
    - navigation.tabs
  custom_dir: "docs/overrides"
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Dark mode
      primary: black
      accent: indigo

    # Light Mode
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Light mode
      primary: indigo
      accent: indigo

markdown_extensions:
  - admonition
  - markdown_include.include:
      base_path: docs/
  - pymdownx.details
  - attr_list
  - abbr
  - def_list
  - footnotes
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite:
  - pymdownx.snippets:
      base_path: docs/
  - pymdownx.tabbed:
      alternate_style: true

plugins:
    - search
    - mkdocstrings
    - git-revision-date-localized:
          enable_creation_date: true
          type: timeago
    # - pdf-export
    - mkdocs-jupyter:
          include_source: True
          ignore_h1_titles: True
          execute: false
          allow_errors: false
          ignore: ["conf.py"]
          execute_ignore: ["*ignore.ipynb"]


extra:
  generator: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/snowport
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/noah-portman/

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css
  - stylesheets/custom.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js
  - js/render-katex.js

copyright: Copyright &copy; 2025 Noah Portman

nav:
  - Home: index.md
  - CV: cv.md
  - Samples:
    - Summary: samples/summary.md
    - Capstone: samples/capstone.md
    - WCI: samples/wci.md
    - Wetland: samples/wetland.md
    - Natural Capital: samples/natural_capital.md
  - Notebooks:
      - Portfolio:
        - MIT xPRO: notebooks/mitxpro/about.md
        - 1. Patient Scheduling: notebooks/mitxpro/01_prescriptive_data.ipynb
        - 2. Predicting Abnormal Scans: notebooks/mitxpro/02_binary_classification.ipynb
        - 3. Statistical Modeling: notebooks/mitxpro/03_prescriptive_model.ipynb
        - 4. Image Classification: notebooks/mitxpro/04_image_classification.ipynb
        - 5. Predictive Modeling: notebooks/mitxpro/05_XGBoost.ipynb
      - Portgeo: notebooks/portgeo.md
      - Other:
        - Integrated Gradients: notebooks/other/integrated_gradients.ipynb

