site_name: noportman.github.io
site_description: A python portfolio
site_author: noportman
# site_url: https://noportman.github.io
# repo_url: https://github.com/noportman/noportman.github.io
theme:
  name: material
  font:
    text: Roboto
    # code: Regular
  logo: assets/images/logo.png
  favicon: assets/images/favicon.png
  # icon:
  features:
    - navigation.footer
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: indigo
      accent: indigo

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: indigo
      accent: indigo

markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite:
  - pymdownx.snippets:
  - pymdownx.superfences:
  - pymdownx.tabbed:
      alternate_style: true

plugins:
    - search
    - mkdocstrings
    # - git-revision-date:
    - git-revision-date-localized:
          enable_creation_date: true
          type: timeago
    # - pdf-export
    - mkdocs-jupyter:
          include_source: True
          ignore_h1_titles: True
          execute: False
          allow_errors: false
          ignore: ["conf.py"]
          execute_ignore: ["*ignore.ipynb"]

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/noportman
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/noah-portman/

copyright: Copyright &copy; 2025 Noah Portman

nav:
  - Welcome: index.md
  - CV: cv.md
  - Portfolio:
      - Overview: overview.md
      - Patient Scheduling: notebooks/01_prescriptive_data.ipynb
      - Predicting Abnormal Scans: notebooks/02_binary_classification.ipynb
      - Statistical Modeling: notebooks/03_prescriptive_model.ipynb
      - Image Classification: notebooks/04_image_classification.ipynb
      - Predictive Modeling: notebooks/05_XGBoost.ipynb
  - Writing Samples: samples.md

