name: Deploy MkDocs Site

on:
  push:
    branches:
      - main  # or master

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt -r requirements_dev.txt

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Build the site
        run: mkdocs build

      - name: Add CNAME file
        run: echo "noahportman.com" > site/CNAME

      - name: Deploy with MKDocs
        run: mkdocs gh-deploy --clean --force 